seo:
  site_name: Sebastian Russold Sommelier
  title: Sebastian Russold Sommelier
  url: https://russold-sommelier.com
  description: >-
    1. Platz Sommmelier Trophy â€œDeutschlands Bester Sommelier 2021/22 Sommelier
    Union e.v. Gastronomie & Handel. Moderation Events & Messen. Privater
    Sommelier
  keywords: Sommelier, Moderation, Gastronomie, Weinkarte, Weinkeller
  type: Website
  social_image: /images/sommelier_trophy_social.jpg
  author: Sebastian Russold, Anna Kauker
  favicon_image:
social:
  instagram_username: sebastianrussold
  facebook_url: https://www.facebook.com/sebastian.russold
  linkedin_url: >-
    https://de.linkedin.com/in/sebastian-russold?original_referer=https%3A%2F%2Fwww.google.com%2F
design:
  dark-text_color: '#000000'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  link-text_color: '#77a2a9'
  green_color: '#1c2a2c'
  dark_color: '#1c2a2c'
  light_color: '#ffffff'
  v-light_color: '#f9f9f9'
  featured_color: '#6495ed'
  accent_color: '#a74a4a'
